### ISSUE TITLE
MCPSCovid.co NOT WORKING?!?! More than a month old.

### ISSUE THREAD

**Issue by kavipatel04** [jamxu88/mocovid#2]
I tried to access the data but I could only see February. This is more than a month old.  Please fix.

**Comment by jamxu88** [comment]
Per MCPS: Daily case reports are no longer updated following the implementation of the new data-dashboard above. This function stopped on March 1.
This project is now discontinued because MCPS has stopped providing the raw data and their COVID dashboard is functional again. You can find it here: [https://www.montgomeryschoolsmd.org/coronavirus/dashboard/](https://www.montgomeryschoolsmd.org/coronavirus/dashboard/)
